//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student_registation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentReg
    {
        public int id {get; set;}
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Courses { get; set; }
        public string Gender { get; set; }
        public string PhoneCode { get; set; }
        public string Phone { get; set; }
        public string Curr_Address { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Re_Password { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
