//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_name.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class std
    {
        public int id { get; set; }
        public string name { get; set; }
        public string roll { get; set; }
        public string course { get; set; }
        public string email { get; set; }
        public Nullable<long> mobile { get; set; }
        public string password { get; set; }
        public string re_password { get; set; }
    }
}
